Thamer/Thamer/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main_app.urls")),
    path("users/", include("users_app.urls")),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Thamer/main_app/urls.py
from django.urls import path
from . import views

app_name = "main_app"

urlpatterns = [
    path("company/add/", views.add_company, name="add_company"),
    path("", views.entry_page, name="entry_page"),
    path("home/", views.index_page, name="index_page"),
    path("company/add/", views.add_company, name="add_company"),
    path("home/faq_page/", views.faq_page, name="faq_page"),
    path("home/contact_us/", views.contact_us, name="contact_us"),
    path("home/market/", views.market_page, name="market_page"),
    path("companys/update/<company_id>/", views.update_company, name="update_company"),
    path("companys/details/<company_id>/", views.company_detail, name="company_detail"),
    path("companys/delete/<company_id>/", views.delete_company, name="delete_company"),
    path("companys/<company_id>/review/add/", views.add_review, name="add_review"),
    path("home/what_we_do/", views.what_we_do, name="what_we_do"),
    path("home/consultion/", views.consultion_page, name="consultion_page"),
    path("home/over_view/", views.over_view, name="over_view"),
    path("home/companys/", views.company_page, name="company_page"),
    path("home/profile/", views.profile_page, name="profile_page"),
    path("home/dashboard", views.dashboard_page, name="dashboard_page"),
    path("companys/owner_details/<company_id>/", views.onwer_details, name="onwer_details"),
    path("submit/done", views.submit_done, name="submit_done"),

]

Thamer/users_app/urls.py
from django.urls import path
from . import views

app_name = "users_app"

urlpatterns = [
    path("sign_up/", views.signup, name="signup"),
    path("login/", views.login_page, name="login"),
    path("signout/", views.signout_page, name="signout_page"),
    path("no_permission_page/", views.no_permission_page, name="no_permission_page"),
    
]

Thamer/main_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Company(models.Model):
    
        
    CHOICES = (
        ('Energy', 'Energy'),
        ('Materials', 'Materials'),
        (' Media and Entertainment', 'Media and Entertainmen'),
        ('Captial goods', 'Captial goods'),
        ('Commercial & Professional Svc', 'Commercial & Professional Svc'),
        ('Transportation', 'Transportation'),
        ('Consumer Durables', 'Consumer Durables'),
        ('Consumer Services', 'Consumer Services'),
        ('Retailing', 'Retailing'),
        ('Food & Stables Retailing', 'Food & Stables Retailing'),
        ('Food & Beverages', 'Food & Beverages'),
        ('Health care Equipment & Svc', 'Health care Equipment & Svc'),
    )
    name = models.CharField(max_length=2048)
    description = models.TextField()
    local_score = models.FloatField()
    ikteva_score_now = models.FloatField()
    ikteva_score_before= models.FloatField()
    email =  models.CharField(max_length=2048)
    contact_number = models.CharField(max_length=2048)
    instagram_link = models.URLField(blank=True)
    linkdin = models.URLField(blank=True)
    twitter_link = models.URLField(blank=True)
    website = models.URLField(blank=True)
    sectors= models.TextField(max_length=2048,default='')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    pdf_file_ikteva = models.FileField(upload_to='pdf_file_ikteva/', null=True, blank=True)
    pdf_file_local = models.FileField(upload_to='pdf_file_local/', null=True, blank=True)
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')


    def __str__(self) -> str:
        return f"{self.name}"



class Review(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    content = models.TextField()
    rating = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True,null=True)


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    send_time=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

Thamer/main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.models import User, Permission, Group
from django.contrib.auth import authenticate, login, logout
from .models import Company,Review, User,Contact
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render
from django.db.models import Avg



# Create your views here.
@login_required(login_url="/users/login/")

def add_company(request):
    if request.method == "POST":
        name = request.POST.get('name')
        sectors = request.POST.get('sectors')
        local_score = request.POST.get('local_score')
        pdf_file_local = request.FILES.get('pdf_file_local')
        ikteva_score_now = request.POST.get('ikteva_score_now')
        ikteva_score_before = request.POST.get('ikteva_score_before')
        pdf_file_ikteva = request.FILES.get('pdf_file_ikteva')
        description = request.POST.get('description', '')
        email = request.POST.get('email')
        contact_number = request.POST.get('contact_number')

        # Perform validation
        errors = []
        try:
            local_score = int(local_score)
        except ValueError:
            errors.append("Invalid value for Current local Content Score. Please enter a valid number.")

        try:
            ikteva_score_now = int(ikteva_score_now)
        except ValueError:
            errors.append("Invalid value for Current Iktva Score. Please enter a valid number.")

        try:
            ikteva_score_before = int(ikteva_score_before)
        except ValueError:
            errors.append("Invalid value for Last Year Iktva Score. Please enter a valid number.")

        if errors:
            return render(request, "main_app/add_company.html", {'errors': errors})

        # Continue with saving the company if validation passes
        new_company = Company(
            name=name,
            sectors=sectors,
            local_score=local_score,
            pdf_file_local=pdf_file_local,
            ikteva_score_now=ikteva_score_now,
            ikteva_score_before=ikteva_score_before,
            pdf_file_ikteva=pdf_file_ikteva,
            description=description,
            email=email,
            contact_number=contact_number,
            owner=request.user,
            status='pending'
        )

        new_company.save()
        return redirect("main_app:market_page")

    return render(request, "main_app/add_company.html")


def market_page(request: HttpRequest):
    # Show all data inside the model in Market
    companys = Company.objects.all()

    return render(request, "main_app/market.html", {"companys": companys})






def company_detail(request:HttpRequest, company_id):

        #Show each  data inside the model in thier ID


    company = Company.objects.get(id=company_id)

    return render(request, 'main_app/company_detail.html', {"company" : company}) 

def profile_page(request:HttpRequest):

        #Show each  data inside the model in thier ID


    company = Company.objects.all()


    return render(request, 'main_app/profile_page.html', {"company" : company}) 


@login_required(login_url="/users/login/")
def update_company(request:HttpRequest, company_id):

    company = Company.objects.get(id=company_id)

    #updating the Company model
    if request.method == "POST":
        company.name=request.POST["name"]
        company.description = request.POST["description"]
        company.local_score=request.POST["local_score"]
        company.ikteva_score_now=request.POST["ikteva_score_now"]
        company.ikteva_score_before=request.POST["ikteva_score_before"]
        company.email=request.POST["email"]
        company.contact_number =request.POST["contact_number"]
        company.twitter_link = request.POST["twitter_link"]
        company.linkdin= request.POST["linkdin"]
        company.website = request.POST["website"]
        company.instagram_link = request.POST["instagram_link"]



        company.save()

        return redirect("main_app:company_detail", company_id=company.id)

    return render(request, 'main_app/update_company.html', {"company" : company})

@login_required(login_url="/users/login/")
def delete_company(request:HttpRequest, company_id):

    #Delete the company from the model 
    
    company = Company.objects.get(id=company_id)
    company.delete()

    return redirect("main_app:market_page")




def faq_page(request:HttpRequest):
    
# About us HTML
    return render(request, "main_app/faq_page.html")

def entry_page(request:HttpRequest):
    
# About us HTML
    return render(request, "main_app/entry_page.html")




def contact_us(request:HttpRequest):
    if request.method == "POST":
        
        newContact = Contact(name=request.POST['name'],email=request.POST['email'],subject=request.POST['subject'],message=request.POST['message'])
        newContact.save()
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject= request.POST.get('subject')
        message = request.POST.get('message')
        
        form_data = {
            'name':name,
            'email':email,
            'subject':subject,
            'message':message,
        }
        message= '''
        New message:{}

        From: {}
        '''.format(form_data["message"], form_data["email"])
        send_mail(form_data["subject"],message,'fasialalhussin@gmail.com',['fasialalhussin@gmail.com'])

        return redirect("main_app:submit_done")
    return render(request, "main_app/contact_us.html") 



from django.shortcuts import render
from .models import Company

def index_page(request):
    # Fetch all companies
    companys = Company.objects.filter(status='approved')

    # Count the total number of companies
    total_companies = companys.count()

    average_ikteva_score = companys.aggregate(avg_ikteva_score=Avg('ikteva_score_now'))['avg_ikteva_score']
    average_ikteva_score = int(average_ikteva_score) if average_ikteva_score is not None else None
        # Calculate the average local_score
    average_local_score = companys.aggregate(avg_local_score=Avg('local_score'))['avg_local_score']

    # Convert to integer if the average is a whole number
    average_local_score = int(average_local_score) if average_local_score is not None else None


    
    return render(request, 'main_app/index.html', {"companys": companys, "total_companies": total_companies, "average_ikteva_score": average_ikteva_score,"average_local_score": average_local_score})


def dashboard_page(request:HttpRequest):
    
# Home HTML

    return render(request, "main_app/dashboard_page.html")



# Future feature

def add_review(request:HttpRequest, company_id):

    if request.method == "POST":
        company_object = Company.objects.get(id=company_id)
        new_review = Review(company=company_object, user=request.user, content=request.POST["content"], rating=request.POST["rating"])
        new_review.save()

    
    return redirect("main_app:company_detail", company_id=company_id)



def consultion_page(request:HttpRequest):
    
    # payment page HTML

    return render(request, "main_app/consultion_page.html")

def what_we_do(request:HttpRequest):
    
    # payment page HTML

    return render(request, "main_app/what_we_do_page.html")



def over_view(request:HttpRequest):

    # payment page HTML


    return render(request, "main_app/over_view.html")

@login_required(login_url="/users/login/")
def company_page(request:HttpRequest):
    # Retrieve companies associated with the currently logged-in user
    company = Company.objects.filter(owner=request.user)

    # Pass the companies variable to the template in the context dictionary
    return render(request, "main_app/my_compnies.html", {"company": company})


def onwer_details(request:HttpRequest, company_id):

        #Show each  data inside the model in thier ID


    company = Company.objects.get(id=company_id)

    return render(request, 'main_app/onwer_details.html', {"company" : company}) 

def submit_done(request:HttpRequest):

    return render(request,"main_app/submit_done.html")

Thamer/main_app/templates/main_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock%}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href={% static 'assets/img/apple-touch-icon.png' %} rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %} rel="stylesheet">
  <link href={% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %} rel="stylesheet">
  <link href={% static 'assets/vendor/boxicons/css/boxicons.min.css' %} rel="stylesheet">
  <link href={% static 'assets/vendor/quill/quill.snow.css' %} rel="stylesheet">
  <link href={% static 'assets/vendor/quill/quill.bubble.css' X} rel="stylesheet">
  <link href={% static 'assets/vendor/remixicon/remixicon.css' %} rel="stylesheet">
  <link href={% static 'assets/vendor/simple-datatables/style.css' %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static 'assets/css/style.css' %} rel="stylesheet" >

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Updated: Sep 18 2023 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'main_app:index_page' %}" class="logo d-flex align-items-center">
        <img src={% static 'assets/img/logo.png' %} alt="">
        <span class="d-none d-lg-block">Thamer</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">

    </div><!-- End Search Bar -->
    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

        </li><!-- End Notification Nav -->

        <li class="nav-item dropdown">

        </li><!-- End Messages Nav -->
          {% if request.user.is_authenticated%}

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                      <i class="bi bi-people"></i>
            <span class="d-none d-md-block dropdown-toggle ps-2">{{request.user.first_name}} {{request.user.last_name}}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{request.user.first_name}} {{request.user.last_name}}</h6>
              <span>{{request.company.name}}</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'main_app:profile_page' %}">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href={% url 'users_app:signout_page' %}>
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>
  {% else %}
          <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-person-circle"></i>
            <button type="button" class="btn btn-outline-primary">Sign Up</button>

          </a><!-- End Messages Icon -->


          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'users_app:login' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Login</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'users_app:signup' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Up</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->
          {% endif %} 

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
      <li class="nav-item">
        <a class="nav-link " href="{% url 'main_app:over_view' %}">
          <i class="bi bi-grid"></i>
          <span>Our business</span>
        </a>
      </li><!-- End Tables Nav -->
      <li class="nav-item">
        <a class="nav-link " href="{% url 'main_app:what_we_do' %}">
          <i class="bi bi-grid"></i>
          <span>Thamer</span>
        </a>
      </li><!-- End Tables Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Catalog</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
                <a href="{% url 'main_app:market_page' %}">
              <i class="bi bi-circle"></i><span>Market</span>
                  {% if request.user.is_authenticated%}
                <a href="{% url 'main_app:consultion_page' %}">
              <i class="bi bi-circle"></i><span>Consultation</span>
              </ul>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
            <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
              <i class="bi bi-menu-button-wide"></i><span>My information</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            </li>
              <li>
                <a href=" {% url 'main_app:company_page' %}">
                  <i class="bi bi-circle"></i><span>Compnies List</span>
                </a>
              </li>
              <li>
                <a href=" {% url 'main_app:add_company' %}">
                  <i class="bi bi-circle"></i><span>Add Company</span>
                </a>
              </li>
            {% endif %} 

        </ul>
      <li class="nav-heading">Pages</li>
          {% if request.user.is_authenticated%}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'main_app:profile_page' %}">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li><!-- End Profile Page Nav -->
        {% endif %} 


      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'main_app:faq_page' %}">
          <i class="bi bi-question-circle"></i>
          <span>F.A.Q</span>
        </a>
      </li><!-- End F.A.Q Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'main_app:contact_us' %}">
          <i class="bi bi-envelope"></i>
          <span>Contact</span>
        </a>
      </li><!-- End Contact Page Nav -->
      </ul>
    </ul>

  </aside><!-- End Sidebar-->

        {% block content%}
        {% endblock %}
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src={% static 'assets/vendor/apexcharts/apexcharts.min.js' %}></script>
  <script src={% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}></script>
  <script src={% static 'assets/vendor/chart.js/chart.umd.js' %}></script>
  <script src={% static 'assets/vendor/echarts/echarts.min.js' %}></script>
  <script src={% static 'assets/vendor/quill/quill.min.js' %}></script>
  <script src={% static 'assets/vendor/simple-datatables/simple-datatables.js' %}></script>
  <script src={% static 'assets/vendor/tinymce/tinymce.min.js' %}></script>
  <script src={% static 'assets/vendor/php-email-form/validate.js' %}></script>

  <!-- Template Main JS File -->
  <script src={% static 'assets/js/main.js' %}></script>

</body>

</html>

Thamer/main_app/templates/main_app/login.html
{% extends 'main_app/base.html'%}
{% load static %}

{% block title %}Sign In{% endblock %}


{% block content %}
  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href="index.html" class="logo d-flex align-items-center w-auto">
                  <img src="assets/img/logo.png" alt="">
                  <span class="d-none d-lg-block">Thamer</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                    <p class="text-center small">Enter your username & password to login</p>
                  </div>

                  <form action="{% url 'main_app:login' %}" method="POST" enctype="multipart/form-data" class="row g-3 needs-validation" novalidate>
                              {% csrf_token %}


                    <div class="col-12">
                      <label for="yourUsername" class="form-label">Username</label>
                      <div class="input-group has-validation">
                        <span class="input-group-text" id="inputGroupPrepend">@</span>
                        <input type="text" name="user_name" class="form-control"required>
                        <div class="invalid-feedback">Please enter your username.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>


                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Login</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Don't have account? <a href="{% url 'main_app:signup' %}">Create an account</a></p>
                    </div>
                  </form>

                </div>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->
    {% endblock %}

Thamer/main_app/templates/main_app/my_compnies.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block title %}My Company{% endblock %}
{% block content%}

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>My Compnies</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item active">My Compnies</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->
    {% if company %}
    <section class="section">
      <div class="row">
        <div class="col-lg-10">
      {% for company in company %}
          <div class="card">
            <div class="card-body">
            <div class="info-item d-flex flex-column justify-content-center align-items-center">
              <a href="{% url 'main_app:onwer_details' company.id %}" class="card-title">{{company.name}}</a>
              <p>{{company.description}} </p>

              <!-- Tooltips Examples -->
        <div class="mb-3">
            <a href="{% url 'main_app:update_company' company.id %}" class="btn btn-primary rounded-pill">Update company</a>
          <!-- ***** Delete the company Id , Id beacome Null***** -->
            <a href="{% url 'main_app:delete_company' company.id %}" class="btn btn-danger rounded-pill">Delete company</a>

        </div>

              <!-- End Tooltips Examples -->

            </div>
          </div>
         {% endfor %}
        </div>

      </div>
  {% else %}
    <p>You have not created any companies yet.</p>
  {% endif %}
    </section>

  </main><!-- End #main -->
{% endblock %}

Thamer/main_app/templates/main_app/onwer_details.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block title %}{{ company.name }}{% endblock%}


{% block content%}
  <main id="main" class="main">

    <section class="section">
        <div class="pagetitle">
      <h1>Chart.js</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'main_app:index_page' %}">Home</a></li>
          <li class="breadcrumb-item">{{company.name}}</li>
          <li class="breadcrumb-item active">Details</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{company.name}}</h5>
              <p>{{company.description}}</p>
              <!-- End Tooltips Examples -->

            </div>
          </div>

        </div>

      </div>
    </section>
    <section class="section">
  <div class="row">

    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Line Chart</h5>

          <!-- Line Chart -->
          <canvas id="lineChart" style="max-height: 400px;"></canvas>
          <script>
            document.addEventListener("DOMContentLoaded", () => {
              new Chart(document.querySelector('#lineChart'), {
                type: 'line',
                data: {
                  labels: ['#', '2019', '2023'],
                  datasets: [{
                    label: 'Line Chart',
                    data: [0, {{company.ikteva_score_before}}, {{company.ikteva_score_now}}],
                    fill: false,
                    borderColor: 'rgb(75, 192, 192)',
                    tension: 0.1
                  }]
                },
                options: {
                  scales: {
                    y: {
                      beginAtZero: true
                    }
                  }
                }
              });
            });
          </script>
          <!-- End Line Chart -->

        </div>
      </div>
    </div>

    <!-- Company Info -->
    <div class="card col-lg-6">
      <div class="card-body">
        <h5 class="card-title">Company Info</h5>
        <p>Here is Company Details About their Score</p>

        <!-- List group With badges -->
        <ul class="list-group">
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Local Content
            <span class="badge bg-primary rounded-pill">{{company.local_score}}</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Iktva Score 5 Years Ago
            <span class="badge bg-primary rounded-pill">{{company.ikteva_score_before}}</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Current Iktva Score
            <span class="badge bg-primary rounded-pill">{{company.ikteva_score_now}}</span>
          </li>
        </ul><!-- End List With badges -->
        <h5 class="card-title">Social Media:</h5>

        <p>Contact number:{{company.contact_number}}</p>
        <p>Email: {{company.email}}</p>
        <div class="d-flex">
          <a href="{{company.website}}" class="fa fa-google"></a>
          <a href="{{company.linkdin}}" class="fa fa-linkedin"></a>
          <a href="{{company.instagram_link}}" class="fa fa-instagram"></a>
        </div>
                  {% if request.user.is_authenticated %}
    <a class="btn btn-primary rounded-pill" href="{% url 'main_app:update_company' company.id %}" role="button">update info</a>
    <a href="{% url 'main_app:delete_company' company.id %}" class="btn btn-danger rounded-pill">Delete company</a>
    {% endif %}

      </div>
    </div>

  </div>

</section>

<style>
  .fa {
    padding: 10px;
    font-size: 30px;
    width: 50px;
    text-align: center;
    margin: 5px 2px;
  }

  .fa:hover {
    opacity: 0.7;
  }

  .fa-facebook {
    background: #3B5998;
    color: white;
  }
  
  .fa-twitter {
    background: #55ACEE;
    color: white;
  }

  .fa-google {
    background: #dd4b39;
    color: white;
  }

  .fa-linkedin {
    background: #007bb5;
    color: white;
  }

  .fa-instagram {
    background: #125688;
    color: white;
  }

</style>
  </main><!-- End #main -->



        
{% endblock %}